param(
    [ValidateSet('smoke', 'full')][string]$Mode = 'smoke',
    [ValidatePattern('^[a-zA-Z0-9_-]*$')][string]$Tag = ''
)
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$launcher=Join-Path $PSScriptRoot 'run_local.ps1';$runRoot=Join-Path $root 'logs/rsl_rl/unitree_b2w_stair'
$parents=@(
 [pscustomobject]@{Seed=54;Directory='2026-09-23_11-02-18_stair_basevel_control57_2048_20260923_seed54_full';Sha='49c50eabfc3d9ce640dc3cc46fb15f45fb8f071351e53a768afc2a406b474801'},
 [pscustomobject]@{Seed=55;Directory='2026-09-23_11-04-25_stair_basevel_control57_2048_20260923_seed55_full';Sha='f5d7403f98853374b3cdaf6dc329461b29f0f0658e308c0d6a47b890c2371ff2'})
$iterations=if($Mode-eq'smoke'){'1'}else{'25'};$jobs=@()
foreach($item in $parents){$parent=Join-Path (Join-Path $runRoot $item.Directory) 'model_398.pt';if((Get-FileHash $parent -Algorithm SHA256).Hash.ToLowerInvariant()-ne$item.Sha){throw 'Parent hash mismatch'};$suffix=if($Tag){"${Mode}_${Tag}"}else{$Mode};$label="stair_moving_anchor10_2048_20260923_seed$($item.Seed)_$suffix";$stdout=Join-Path $root "logs/train_$label.stdout.log";$stderr=Join-Path $root "logs/train_$label.stderr.log";if((Test-Path $stdout)-or(Test-Path $stderr)){throw "Output exists for $label"};$cli=@('-NoProfile','-ExecutionPolicy','Bypass','-File',('"'+$launcher+'"'),'scripts/train_stair_b2w.py','--task','RobotLab-Isaac-Velocity-Rough-Unitree-B2W-v0','--headless','--parent-checkpoint',('"'+$parent+'"'),'--fresh-optimizer','--teacher-anchor-weight','10.0','--stop-speed-reward-weight','1.0','--diverse-replay-commands','--stop-on-landing','--restart-after-stop','--cycle-protocol-v3','--landing-tiles-fraction','0.1','--landing-start-probability','1.0','--inverse-rough-fraction','0.05','--max-stair-rise','0.16','--min-stair-run','0.30','--brake-profile','--brake-distance','1.2','--brake-min-speed','0.25','--up-fraction','0.35','--rough-replay-fraction','0.15','--num_envs','2048','--max_iterations',$iterations,'--seed',"$($item.Seed)",'--run_name',$label);if($Mode-eq'smoke'){$cli+=@('--reset-probe','--rough-reset-probe','--replay-command-probe')};$p=Start-Process powershell.exe -ArgumentList $cli -WorkingDirectory $root -WindowStyle Hidden -RedirectStandardOutput $stdout -RedirectStandardError $stderr -PassThru;$jobs += [pscustomobject]@{Label=$label;Process=$p;Stdout=$stdout;Stderr=$stderr};Write-Output "START $label PID=$($p.Id) actor=57 action=16"}
foreach($j in $jobs){$j.Process.WaitForExit();$j.Process.Refresh();$loaded=Select-String $j.Stdout -Pattern 'B2W_STAIR_PARENT_WEIGHTS_LOADED fresh_optimizer=true' -Quiet;$installed=Select-String $j.Stdout -Pattern 'B2W_TEACHER_ANCHOR=' -Quiet;$updated=Select-String $j.Stdout -Pattern 'B2W_TEACHER_ANCHOR_UPDATE=' -Quiet;$trained=Select-String $j.Stdout -Pattern 'Training time:' -Quiet;$probes=$Mode-ne'smoke'-or((Select-String $j.Stdout -Pattern 'B2W_LANDING_RESET_PROBE=' -Quiet)-and(Select-String $j.Stdout -Pattern 'B2W_INVERSE_RESET_PROBE=' -Quiet)-and(Select-String $j.Stdout -Pattern 'B2W_REPLAY_COMMAND_PROBE=' -Quiet));Write-Output "DONE $($j.Label) exit=$($j.Process.ExitCode) loaded=$loaded installed=$installed updated=$updated trained=$trained probes=$probes";if($j.Process.ExitCode-ne0-or-not$loaded-or-not$installed-or-not$updated-or-not$trained-or-not$probes){throw "Run failed: $($j.Label)"}}
